module.exports = [
    "Barbell Bench Press",
    "Incline Barbell Bench Press",
    "Dumbbell Bench Press",
    "Incline Dumbbell Press",
    "Push-Ups",
    "Dips",
    "Cable Flys",
    "Overhead Press (OHP)",
    "Seated Dumbbell Shoulder Press",
    "Lateral Raises",
    "Front Raises",
    "Face Pulls",
    "Pull-Ups",
    "Chin-Ups",
    "Lat Pulldowns",
    "Barbell Rows",
    "Dumbbell Rows",
    "Seated Cable Rows",
    "Deadlift",
    "Romanian Deadlift (RDL)",
    "Barbell Squat",
    "Front Squat",
    "Leg Press",
    "Leg Extensions",
    "Leg Curls",
    "Lunges",
    "Bulgarian Split Squats",
    "Calf Raises",
    "Barbell Bicep Curl",
    "Dumbbell Bicep Curl",
    "Hammer Curls",
    "Preacher Curls",
    "Tricep Pushdowns",
    "Skullcrushers",
    "Overhead Tricep Extension",
    "Plank",
    "Crunches",
    "Leg Raises",
    "Russian Twists",
    "Farmers Walk"
];
