module.exports = [
    { name: "Barbell Bench Press", target: "Chest", secondary: "Triceps, Shoulders" },
    { name: "Incline Barbell Bench Press", target: "Chest", secondary: "Triceps, Shoulders" },
    { name: "Dumbbell Bench Press", target: "Chest", secondary: "Triceps, Shoulders" },
    { name: "Incline Dumbbell Press", target: "Chest", secondary: "Triceps, Shoulders" },
    { name: "Push-Ups", target: "Chest", secondary: "Triceps, Shoulders" },
    { name: "Dips", target: "Chest", secondary: "Triceps, Shoulders" },
    { name: "Cable Flys", target: "Chest", secondary: "Triceps, Shoulders" },
    { name: "Overhead Press (OHP)", target: "Shoulders", secondary: "Triceps" },
    { name: "Seated Dumbbell Shoulder Press", target: "Shoulders", secondary: "Triceps" },
    { name: "Lateral Raises", target: "Shoulders", secondary: "Triceps" },
    { name: "Front Raises", target: "Shoulders", secondary: "Triceps" },
    { name: "Face Pulls", target: "Back", secondary: "Biceps, Shoulders" },
    { name: "Pull-Ups", target: "Back", secondary: "Biceps, Shoulders" },
    { name: "Chin-Ups", target: "Back", secondary: "Biceps, Shoulders" },
    { name: "Lat Pulldowns", target: "Back", secondary: "Biceps, Shoulders" },
    { name: "Barbell Rows", target: "Back", secondary: "Biceps, Shoulders" },
    { name: "Dumbbell Rows", target: "Back", secondary: "Biceps, Shoulders" },
    { name: "Seated Cable Rows", target: "Back", secondary: "Biceps, Shoulders" },
    { name: "Deadlift", target: "Hamstrings", secondary: "Glutes, Back" },
    { name: "Romanian Deadlift (RDL)", target: "Hamstrings", secondary: "Glutes, Back" },
    { name: "Barbell Squat", target: "Quads", secondary: "Glutes, Hamstrings" },
    { name: "Front Squat", target: "Quads", secondary: "Glutes, Hamstrings" },
    { name: "Leg Press", target: "Quads", secondary: "Glutes, Hamstrings" },
    { name: "Leg Extensions", target: "Quads", secondary: "Glutes, Hamstrings" },
    { name: "Leg Curls", target: "Hamstrings", secondary: "Glutes, Back" },
    { name: "Lunges", target: "Quads", secondary: "Glutes, Hamstrings" },
    { name: "Bulgarian Split Squats", target: "Quads", secondary: "Glutes, Hamstrings" },
    { name: "Calf Raises", target: "Calves", secondary: "" },
    { name: "Barbell Bicep Curl", target: "Biceps", secondary: "Forearms" },
    { name: "Dumbbell Bicep Curl", target: "Biceps", secondary: "Forearms" },
    { name: "Hammer Curls", target: "Biceps", secondary: "Forearms" },
    { name: "Preacher Curls", target: "Biceps", secondary: "Forearms" },
    { name: "Tricep Pushdowns", target: "Triceps", secondary: "Shoulders" },
    { name: "Skullcrushers", target: "Triceps", secondary: "Shoulders" },
    { name: "Overhead Tricep Extension", target: "Triceps", secondary: "Shoulders" },
    { name: "Plank", target: "Abs", secondary: "" },
    { name: "Crunches", target: "Abs", secondary: "" },
    { name: "Leg Raises", target: "Abs", secondary: "" },
    { name: "Russian Twists", target: "Abs", secondary: "" },
    { name: "Farmers Walk", target: "Forearms", secondary: "Shoulders, Back" }
];
